name: test
"on":
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Go Cache
        uses: actions/cache@v2
        with:
          path: |-
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-cache-${{ hashFiles('./go.sum') }}
          restore-keys: ${{ runner.os }}-go-cache-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - id: cache-go-sdk
        name: Setup Go SDK Cache
        uses: actions/cache@v2
        with:
          path: |-
            ~/sdk/go1.18beta2
            ~/go/bin/go1.18beta2
          key: go1.18beta2
      - name: Setup Go1.18beta2
        if: steps.cache-go-sdk.outputs.cache-hit != 'true'
        run: |-
          go install golang.org/dl/go1.18beta2@latest
          go1.18beta2 download
          go1.18beta2 env
      - name: Go Test
        run: go1.18beta2 test ./...
